### ISSUE TITLE
An option to not send the user back to the landing page after emptying the queue

### ISSUE THREAD

**Issue by k7bura** [SWViewer/tool-swviewer#8]
A small annoyance, really, but if you [r]evert the last diff in the queue, the software sends you back to the landing page, meaning the hotkeys (specially [space]) stop working, so you have to click back on a diff to go back to using the hotkeys. If possible, I'd suggest adding an option where, if reverting the last diff in the queue, instead show the new diff so the user remains in the queue.
Isabelle 🔔 11:21, 2 September 2020 (UTC)
https://meta.wikimedia.org/w/index.php?diff=20416162

**Comment by ajbura** [comment]
fixed in beta

**Comment by ajbura** [comment]
hotkeys now work on welcome page
